// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcDist_Geo
Rcpp::NumericVector calcDist_Geo(Rcpp::NumericMatrix xy, double refx, double refy);
RcppExport SEXP _GeoDist_calcDist_Geo(SEXP xySEXP, SEXP refxSEXP, SEXP refySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type refx(refxSEXP);
    Rcpp::traits::input_parameter< double >::type refy(refySEXP);
    rcpp_result_gen = Rcpp::wrap(calcDist_Geo(xy, refx, refy));
    return rcpp_result_gen;
END_RCPP
}
// calcDist
Rcpp::NumericVector calcDist(Rcpp::NumericMatrix xy);
RcppExport SEXP _GeoDist_calcDist(SEXP xySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xy(xySEXP);
    rcpp_result_gen = Rcpp::wrap(calcDist(xy));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _GeoDist_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _GeoDist_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _GeoDist_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _GeoDist_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeoDist_calcDist_Geo", (DL_FUNC) &_GeoDist_calcDist_Geo, 3},
    {"_GeoDist_calcDist", (DL_FUNC) &_GeoDist_calcDist, 1},
    {"_GeoDist_rcpparma_hello_world", (DL_FUNC) &_GeoDist_rcpparma_hello_world, 0},
    {"_GeoDist_rcpparma_outerproduct", (DL_FUNC) &_GeoDist_rcpparma_outerproduct, 1},
    {"_GeoDist_rcpparma_innerproduct", (DL_FUNC) &_GeoDist_rcpparma_innerproduct, 1},
    {"_GeoDist_rcpparma_bothproducts", (DL_FUNC) &_GeoDist_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeoDist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
