# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcDist_Geo <- function(xy, refx, refy) {
    .Call(`_GeoDist_calcDist_Geo`, xy, refx, refy)
}

calcDist <- function(xy) {
    .Call(`_GeoDist_calcDist`, xy)
}

rcpparma_hello_world <- function() {
    .Call(`_GeoDist_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_GeoDist_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_GeoDist_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_GeoDist_rcpparma_bothproducts`, x)
}

