# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcDist_Geo <- function(latlon, lat, lon) {
    .Call(`_GeoDist_calcDist_Geo`, latlon, lat, lon)
}

calcDist <- function(latlon) {
    .Call(`_GeoDist_calcDist`, latlon)
}

